import type { ActivityLogEntry, Bolo, DispatchCall, DispatchUnit, NewCallForm } from "./types";

export const fireIncidentTypes = [
  "Structure fire",
  "Vehicle fire",
  "Brush fire",
  "Alarm activation",
  "Hazmat",
  "Rescue",
  "Medical assist",
];

export const emsIncidentTypes = [
  "Medical emergency",
  "Trauma",
  "Cardiac",
  "Overdose",
  "Unconscious person",
  "MVA injuries",
  "Psychiatric crisis",
];

export const fireUnitTypes = [
  "Engine",
  "Ladder",
  "Rescue",
  "Battalion",
  "Brush",
  "Tender",
  "Fire command",
];

export const emsUnitTypes = ["Medic", "Ambulance", "Supervisor", "Rescue", "Air medical"];

export const towUnitTypes = [
  "Standard tow",
  "Flatbed",
  "Heavy wrecker",
  "Impound",
  "Roadside assistance",
];

export const initialCallForm: NewCallForm = {
  callerName: "",
  callerPhone: "",
  description: "",
  involvedPersons: "",
  involvedVehicles: "",
  location: "",
  postal: "",
  priority: "Medium",
  serviceType: "Law Enforcement",
  type: "",
};

export const sampleCalls: DispatchCall[] = [
  {
    assignedUnits: ["2L-14", "2L-22"],
    callNumber: "C-2026-0142",
    callerName: "Anonymous",
    callerPhone: "Blocked",
    description: "Multiple reports of a reckless driver striking parked cars.",
    id: "call-1",
    involvedPersons: "Unknown driver",
    involvedVehicles: "Black Sultan RS, partial plate 82Q",
    location: "Strawberry Ave / Innocence Blvd",
    notesCount: 5,
    openedAt: "21:42",
    postal: "829",
    priority: "High",
    serviceType: "Law Enforcement",
    status: "Assigned",
    type: "Traffic collision",
  },
  {
    assignedUnits: ["E-7", "M-3", "BAT-1"],
    callNumber: "C-2026-0143",
    callerName: "M. Roberts",
    callerPhone: "555-0182",
    description: "Smoke visible from second floor, occupants evacuating.",
    id: "call-2",
    involvedPersons: "Building occupants",
    involvedVehicles: "",
    location: "Alta St Apartments",
    notesCount: 3,
    openedAt: "21:47",
    postal: "716",
    priority: "Critical",
    serviceType: "Fire",
    status: "Enroute",
    type: "Structure fire",
  },
  {
    assignedUnits: ["M-12"],
    callNumber: "C-2026-0144",
    callerName: "LS Transit",
    callerPhone: "555-0199",
    description: "Unconscious person at bus stop, breathing status unknown.",
    id: "call-3",
    involvedPersons: "Unknown patient",
    involvedVehicles: "",
    location: "Vespucci Blvd Bus Stop",
    notesCount: 2,
    openedAt: "21:52",
    postal: "603",
    priority: "High",
    serviceType: "EMS",
    status: "On Scene",
    type: "Unconscious person",
  },
];

export const sampleUnits: DispatchUnit[] = [
  {
    agency: "LSPD",
    callsign: "2L-14",
    currentCall: "C-2026-0142",
    id: "unit-1",
    lastUpdate: "21:53",
    location: "Postal 829",
    memberName: "Officer Hayes",
    specialty: "Patrol",
    status: "On Scene",
    type: "Law Enforcement",
  },
  {
    agency: "LSPD",
    callsign: "2L-22",
    currentCall: "C-2026-0142",
    id: "unit-2",
    lastUpdate: "21:50",
    location: "Innocence Blvd",
    memberName: "Officer Park",
    specialty: "Traffic",
    status: "Enroute",
    type: "Law Enforcement",
  },
  {
    agency: "LSFD",
    callsign: "E-7",
    currentCall: "C-2026-0143",
    id: "unit-3",
    lastUpdate: "21:51",
    location: "Alta St",
    memberName: "Capt. Irwin",
    specialty: "Engine",
    status: "Enroute",
    type: "Fire",
  },
  {
    agency: "LSFD",
    callsign: "BAT-1",
    currentCall: "C-2026-0143",
    id: "unit-4",
    lastUpdate: "21:49",
    location: "Station 1",
    memberName: "Battalion Stone",
    specialty: "Fire command",
    status: "Busy",
    type: "Fire",
  },
  {
    agency: "SAEMS",
    callsign: "M-12",
    currentCall: "C-2026-0144",
    id: "unit-5",
    lastUpdate: "21:54",
    location: "Postal 603",
    memberName: "Medic Santos",
    specialty: "Medic",
    status: "On Scene",
    type: "EMS",
  },
  {
    agency: "Downtown Tow",
    callsign: "TOW-4",
    currentCall: "None",
    id: "unit-6",
    lastUpdate: "21:46",
    location: "Impound lot",
    memberName: "R. Cooper",
    specialty: "Flatbed",
    status: "Available",
    type: "Tow",
  },
  {
    agency: "SAST",
    callsign: "5A-31",
    currentCall: "None",
    id: "unit-7",
    lastUpdate: "21:55",
    location: "Senora Fwy",
    memberName: "Trooper Allen",
    specialty: "Highway",
    status: "Panic",
    type: "Law Enforcement",
  },
];

export const sampleBolos: Bolo[] = [
  {
    associated: "Black Sultan RS, partial 82Q",
    createdAt: "21:38",
    createdBy: "DISP-02",
    description: "Vehicle fled a collision scene and may have front-end damage.",
    id: "bolo-1",
    lastKnownLocation: "Strawberry Ave northbound",
    priority: "High",
    status: "Active",
    title: "Hit-and-run suspect vehicle",
    type: "Vehicle",
  },
  {
    associated: "John Doe, red hoodie",
    createdAt: "20:15",
    createdBy: "DISP-04",
    description: "Subject made threats toward responding officers during prior call.",
    id: "bolo-2",
    lastKnownLocation: "Legion Square",
    priority: "Medium",
    status: "Under Review",
    title: "Officer safety advisory",
    type: "Officer safety",
  },
];

export const sampleLog: ActivityLogEntry[] = [
  {
    actor: "DISP-02",
    id: "log-1",
    message: "C-2026-0142 assigned to 2L-14 and 2L-22.",
    related: "C-2026-0142",
    timestamp: "21:43",
  },
  {
    actor: "SYSTEM",
    id: "log-2",
    message: "Signal 100 cleared for primary channel.",
    timestamp: "21:45",
  },
  {
    actor: "DISP-01",
    id: "log-3",
    message: "Fire tone activated for structure fire response.",
    related: "C-2026-0143",
    timestamp: "21:47",
  },
];
